[[models]]
name = "black-forest-labs/FLUX.1-schnell"
guidance_scale = 0.0
num_inference_steps = 4
true_cfg_scale = 1.0

[[models]]
name = "black-forest-labs/FLUX.1-dev"
guidance_scale = 3.5
num_inference_steps = 8
true_cfg_scale = 1.0
